Added Application Insights Functionality
cmu-sei/Identity pull request #19
Opened 2023-06-16 17:44 UTC by sei-npacheco

Added functionality to add application insights to the Identity Server.

2023-06-16 21:41 UTC, sei-jmattson requested changes

2023-06-16 21:41 UTC, sei-jmattson commented on src/IdentityServer/appsettings.conf
> +#ConnectionString =
What do you think about making this it's own config section? `Insights__ConnectionString = `; that keeps the setting isolated and allows for adding other Insight options without having to recompile anything.

Then you could pass that config section...
```cs
if (string.IsNullOrEmpty(Configuration["Insights:ConnectionString"]).Equals(false))
                services.AddApplicationInsightsTelemetry(Configuration.GetSection("Insights"));
```

2023-06-16 21:41 UTC, sei-jmattson commented on src/IdentityServer/IdentityServer.csproj
> +    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.20.0" />
2.21 is latest

2023-06-21 16:58 UTC, sei-npacheco commented on src/IdentityServer/appsettings.conf
> +#ConnectionString =
I think that's a good idea. I have already applied those changes to my branch. I also needed to add an Application Insights Library. To be able to pass the Connection String for it to connect to Azure, I needed to add "option.ConnectionString" when adding the Telemetry service.

With these new changes, I was able to test them on my local environment and was able to get the logs from the Identity Server. Let me know if there are any additional changes needed.

2023-06-23 17:06 UTC, merged